src/main/java/bio/terra/rbs/db/ResourceState.java
src/main/resources/db/changesets/20200925_initial_schema.yaml
src/test/java/bio/terra/rbs/db/BackwardsCompatibilityTest.java

Those are needed in delete resource flight

[PF-162] Add two more enums in resource state for delete resource

---

src/main/java/bio/terra/rbs/app/controller/GlobalExceptionHandler.java
src/main/java/bio/terra/rbs/common/exception/NotFoundException.java

Will be used in handout resource endpoints

[PF-131] Add NotFoundException

---

build.gradle
src/main/java/bio/terra/rbs/service/resource/flight/CreateNetworkStep.java
src/main/java/bio/terra/rbs/service/resource/flight/CreateRouteStep.java
src/main/java/bio/terra/rbs/service/resource/flight/CreateSubnetsStep.java
src/main/java/bio/terra/rbs/service/resource/flight/GoogleProjectCreationFlight.java
src/main/java/bio/terra/rbs/service/resource/flight/GoogleUtils.java
src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java

https://github.com/broadinstitute/gcp-dm-templates/blob/eeee90fa4619b273d07206a867b01914cdeb0a30/templates/network.py#L79

[PF-163] Creates static custom route when network monitoring enabled

---

src/main/java/bio/terra/rbs/app/controller/RbsApiController.java
src/main/java/bio/terra/rbs/db/RbsDao.java
src/main/java/bio/terra/rbs/service/pool/PoolService.java
src/main/java/bio/terra/rbs/service/resource/flight/GoogleUtils.java
src/main/resources/api/service_openapi.yaml
src/test/java/bio/terra/rbs/app/controller/RbsApiControllerTest.java
src/test/java/bio/terra/rbs/common/BackwardsCompatibilityTest.java
src/test/java/bio/terra/rbs/db/RbsDaoTest.java
src/test/java/bio/terra/rbs/service/pool/PoolServiceTest.java
terra-rbs-client/gradle.properties

I think it might be helpful if client want to know if pool is ready to use. 
Will add more if we need in the future.

[PF-216] Initial get pool info endpoint

---

src/main/java/bio/terra/rbs/service/resource/FlightManager.java
src/main/java/bio/terra/rbs/service/resource/FlightSubmissionFactoryImpl.java
src/main/java/bio/terra/rbs/service/resource/flight/CreateProjectStep.java
src/main/java/bio/terra/rbs/service/resource/flight/DeleteProjectStep.java
src/main/java/bio/terra/rbs/service/resource/flight/FinishResourceDeletionStep.java
src/main/java/bio/terra/rbs/service/resource/flight/GoogleProjectDeletionFlight.java
src/main/java/bio/terra/rbs/service/resource/flight/GoogleUtils.java
src/main/java/bio/terra/rbs/service/resource/flight/InitialResourceDeletionStep.java
src/main/java/bio/terra/rbs/service/resource/flight/UpdateResourceAsDeletedStep.java
src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
src/test/java/bio/terra/rbs/integration/DeleteProjectFlightIntegrationTest.java
src/test/java/bio/terra/rbs/integration/IntegrationUtils.java

Hi Will, sorry for another large PR. But I think the majority line diffs are moving common things into `IntegratinUtils` then Creation/Deletion integration test can both use.  Let me know if I should split this into small PRs

[PF-143] delete resource flight

---

build.gradle
src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
src/test/java/bio/terra/rbs/integration/IntegrationUtils.java

Context: https://docs.google.com/document/d/1xt7F_tqSqQ1eCYr-zQ4CJWxQD11BXNkCo4I41Hw3Q2s/edit#

[PF-135] Setup cloud profiler

---

src/main/java/bio/terra/rbs/service/resource/flight/StepUtils.java
src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
src/test/java/bio/terra/rbs/integration/IntegrationUtils.java

Also make IAM part of the `FullGcpProject`
This saves ~30 minutes

[PF-217] Boost test step2: Use one test to verifies we can insert the same step twice

---

build.gradle
src/main/java/bio/terra/rbs/app/configuration/CrlConfiguration.java
src/main/java/bio/terra/rbs/service/pool/GcpResourceConfigValidator.java
src/main/java/bio/terra/rbs/service/resource/flight/CreateBucketStep.java
src/main/java/bio/terra/rbs/service/resource/flight/CreateStorageLogBucketStep.java
src/main/java/bio/terra/rbs/service/resource/flight/GoogleProjectCreationFlight.java
src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
src/test/java/bio/terra/rbs/integration/IntegrationUtils.java
src/test/java/bio/terra/rbs/service/pool/ResourceConfigValidatorTest.java

This has 180 days life cycle and an WRITER ACL. 
See: https://github.com/broadinstitute/gcp-dm-templates/blob/eeee90fa4619b273d07206a867b01914cdeb0a30/templates/project.py#L165

[PF-218]: Creates storage logs

---

src/main/java/bio/terra/rbs/service/resource/flight/CreateProjectStep.java
src/main/java/bio/terra/rbs/service/resource/flight/CreateSubnetsStep.java
src/main/java/bio/terra/rbs/service/resource/flight/GoogleUtils.java
src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
src/test/java/bio/terra/rbs/integration/IntegrationUtils.java

Related slack thread with:
https://broadinstitute.slack.com/archives/CNXF2BAPJ/p1605025104418400
DM code: https://github.com/broadinstitute/gcp-dm-templates/blob/eeee90fa4619b273d07206a867b01914cdeb0a30/firecloud_project.py#L358

[PF-208] Label project with network, subnetwork and config name

---

src/main/resources/api/service_openapi.yaml

Apache proxy needs this for authN/authZ

[PF-137] Add security schema for RBS endpoint

---

build.gradle
gradle.lockfile
src/main/java/bio/terra/buffer/service/resource/flight/CreateFirewallRuleStep.java
src/main/java/bio/terra/buffer/service/resource/flight/CreateNetworkStep.java
src/main/java/bio/terra/buffer/service/resource/flight/CreateProjectStep.java
src/main/java/bio/terra/buffer/service/resource/flight/CreateRouteStep.java
src/main/java/bio/terra/buffer/service/resource/flight/DeleteDefaultFirewallRuleStep.java
src/main/java/bio/terra/buffer/service/resource/flight/DeleteDefaultFirewallRulesStep.java
src/main/java/bio/terra/buffer/service/resource/flight/DeleteDefaultNetworkStep.java
src/main/java/bio/terra/buffer/service/resource/flight/EnableServicesStep.java
src/main/java/bio/terra/buffer/service/resource/flight/GoogleProjectCreationFlight.java
src/test/java/bio/terra/buffer/integration/CreateProjectFlightIntegrationTest.java

DM code: https://github.com/broadinstitute/gcp-dm-templates/blob/eeee90fa4619b273d07206a867b01914cdeb0a30/templates/project.py#L329

[PF-229]: Delete default VPC

---

build.gradle
src/main/java/bio/terra/buffer/app/configuration/CrlConfiguration.java
src/main/java/bio/terra/buffer/service/resource/FlightMapKeys.java
src/main/java/bio/terra/buffer/service/resource/flight/CreateProjectStep.java
src/main/java/bio/terra/buffer/service/resource/flight/DeleteDefaultServiceAccountStep.java
src/main/java/bio/terra/buffer/service/resource/flight/EnableServicesStep.java
src/main/java/bio/terra/buffer/service/resource/flight/GoogleProjectCreationFlight.java
src/test/java/bio/terra/buffer/integration/CreateProjectFlightIntegrationTest.java

DM code: https://github.com/broadinstitute/gcp-dm-templates/blob/eeee90fa4619b273d07206a867b01914cdeb0a30/templates/project.py#L412

[PF-238] Delete default SA account when creating project

---

src/main/java/bio/terra/buffer/app/configuration/CrlConfiguration.java
src/main/resources/config/perf/pool_schema.yml
src/main/resources/config/perf/resource-config/resource_perf_v1.yml

Set pool size to 1500. Not sure if that is the right value for a perf test.

[PF-254] Add pool config for RBS performance test. 

---

src/main/java/bio/terra/buffer/service/resource/flight/CreateDnsZoneStep.java
src/main/java/bio/terra/buffer/service/resource/flight/CreateFirewallRuleStep.java
src/main/java/bio/terra/buffer/service/resource/flight/CreateNetworkStep.java
src/main/java/bio/terra/buffer/service/resource/flight/CreateRouteStep.java
src/main/java/bio/terra/buffer/service/resource/flight/CreateSubnetsStep.java
src/main/java/bio/terra/buffer/service/resource/flight/GoogleUtils.java

Instead of get then create, use create directly and catch 409 error code.

[no ticket] Catch conflict error when creating cloud resouces 

---

README.md

I found this is helpful and saves my time

[no ticket]Add more tips in readme

---

src/main/resources/config/tools/resource-config/workspace_manager_v1.yml
src/main/resources/config/tools/resource-config/workspace_manager_v2.yml

Reverts DataBiosphere/terra-resource-buffer#98
Break dev and tools.

Revert "[PF-368] Update ParentPoolId to be the folder created by tereraform."

---

src/main/resources/config/dev/pool_schema.yml
src/main/resources/config/perf/pool_schema.yml
src/main/resources/config/prod/pool_schema.yml
src/main/resources/config/tools/pool_schema.yml
src/main/resources/config/tools/resource-config/cwb_ws_resource_quality_v1.yml
src/main/resources/config/tools/resource-config/cwb_ws_resource_quality_v2.yml

1. Setup pool size per CI's feedback 
2. setup quality for tools RBS
3. Remove some unused pools.

[PF-652]Adjust RBS Pools

---

src/main/resources/config/dev/pool_schema.yml
src/main/resources/config/dev/resource-config/datarepo_v2.yml

We accidentally merged the prod billing project when we should have merged the dev billing project. Here's V2 with the correct stuff.

Use correct billing account for dev

---

src/main/resources/config/alpha/pool_schema.yml
src/main/resources/config/alpha/resource-config/datarepo_v1.yml
src/main/resources/config/perf/pool_schema.yml
src/main/resources/config/perf/resource-config/datarepo_v1.yml
src/main/resources/config/prod/pool_schema.yml
src/main/resources/config/prod/resource-config/datarepo_v1.yml
src/main/resources/config/staging/pool_schema.yml
src/main/resources/config/staging/resource-config/datarepo_v1.yml
src/main/resources/config/tools/pool_schema.yml
src/main/resources/config/tools/resource-config/datarepo_v1.yml

This PR needs to wait until https://github.com/broadinstitute/terraform-ap-deployments/pull/331 is merged so that permissions are correct.

DR-1859 Add pools for TDR alpha, staging, perf, and prod

---

.github/workflows/master_push.yml

https://github.com/google-github-actions/setup-gcloud#-notice

Attempt to fix tag/build/push github task.

---

.github/workflows/master_push.yml

Ugh, sorry guys, looks like I mis-read which branch to use for which repo...  Hopefully 3rd try is a charm.

Attempt to fix tag/build/push github task (take 3).

---

src/main/resources/config/perf/pool_schema.yml
src/main/resources/config/perf/resource-config/cwb_ws_perf_v3.yml
src/main/resources/config/perf/resource-config/vpc_sc_v3.yml
src/main/resources/config/tools/pool_schema.yml
src/main/resources/config/tools/resource-config/cwb_ws_resource_quality_v3.yml
src/main/resources/config/tools/resource-config/vpc_sc_qa-fiab_v2.yml

https://broadworkbench.atlassian.net/browse/CA-1466

CA-1466 Enable default compute SA in perf and fiab

---

src/main/java/bio/terra/buffer/app/configuration/PoolConfiguration.java

Spring create an empty string if the value is specified in application.yml with empty value:
https://github.com/DataBiosphere/terra-resource-buffer/blob/master/src/main/resources/application.yml#L18

[no ticket] Convert system path config from empty to null

---

src/main/resources/config/dev/pool_schema.yml
src/main/resources/config/dev/resource-config/vpc_sc_v7.yml
src/main/resources/config/dev/resource-config/vpc_sc_v8.yml

[RW-7885, PF-1376] Pool config for BigQuery Daily Usage Quota Override

---

README.md

This documents the runtime pool configuration that was added in PF-1009 to help with wider adoption of this capability.

[PF-1411] Document runtime pool configuration.

---

src/main/java/bio/terra/buffer/service/resource/flight/CreateConsumerDefinedQuotaForBigQueryDailyUsageStep.java
src/main/java/bio/terra/buffer/service/resource/flight/GoogleProjectConfigUtils.java
src/main/resources/config/dev/pool_schema.yml
src/main/resources/config/dev/resource-config/vpc_sc_v8.yml
src/main/resources/config/dev/resource-config/vpc_sc_v9.yml
src/main/resources/config/resource_schema.yaml
src/test/java/bio/terra/buffer/integration/CreateProjectFlightIntegrationTest.java

I had the base unit wrong; it was supposed to be in MiB, so I was off by a factor of a million or so.
Add a new config, `vp_sc_v9`.

[RW-7885, PF-1376] update from bytes to MiB

---

src/main/resources/config/dev/pool_schema.yml

Test the functionality in #229 by re-activating the v6 vpc_sc pool. Test changing the size from 300 to 50.

[PF-1415] restore pool vpc_sc_v6

---

src/main/java/bio/terra/buffer/app/controller/SetDisallowedBinderFields.java

https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement

POL-219 plug spring vulnerability

---

README.md

Documentation updates
https://broadworkbench.atlassian.net/browse/PF-1906

[PF-1906] RBS Readme updates

---

.github/workflows/master_push.yml
.github/workflows/test-runner-nightly-perf.yml
.github/workflows/test.yml
.github/workflows/trivy.yml

From https://github.com/verily-src/terra-service-resource-buffer/pull/103

[PF-1908] Upgrade set up actions version from v2 -> v3 for Java 17

---

buffer-clienttests/src/main/java/scripts/utils/BufferServiceUtils.java

https://github.com/DataBiosphere/terra-resource-buffer/actions/runs/5397925111/jobs/9803136245
It is trying to use the old deleted pool

[PF-2880] Update Pool reference for perf tests

---

build.gradle
gradle.lockfile
src/main/resources/application.yml

https://broadworkbench.atlassian.net/browse/WOR-1387

WOR-1387 Update tcl

---

src/main/resources/config/tools/pool_schema.yml
src/main/resources/config/tools/resource-config/cwb_ws_resource_quality_v10.yml

Need to add one more API for enablement based on testing. Note that v9 is being deleted here and v8 is being left, since the only rawls referencing that v9 is in my bee as I held off merging the helmfile PR until I got the functionality working. 
https://github.com/broadinstitute/terra-helmfile/pull/4829

[IA-4525] Add iap api enablement

---

.github/workflows/master_push.yml
.github/workflows/test.yml
.github/workflows/trivy.yml

Some cleanup inspired by https://github.com/DataBiosphere/terra-workspace-manager/pull/1691.
Next I'm working on the SA accounts.

[WOR-1745] Cleanup of gradle/setup-java.

---

build.gradle

Pulled out of https://github.com/DataBiosphere/terra-resource-buffer/pull/315.

Update spring (WOR-1448).

---

build.gradle

Pulled out of https://github.com/DataBiosphere/terra-resource-buffer/pull/315

Update opentelemetry (WOR-1448).

---

build.gradle
terra-resource-buffer-client/build.gradle

Pulled out of https://github.com/DataBiosphere/terra-resource-buffer/pull/320
I ran the branch locally and made sure I could bring up the Swagger page.

Update swagger and opentelemetry (WOR-1448).

---

src/main/java/bio/terra/buffer/service/resource/flight/CreateGkeDefaultSAStep.java

https://broadworkbench.atlassian.net/browse/AN-181

[AN-181] Give default compute SA the secretAccessor role

---

src/main/resources/static/service_openapi.yaml
src/test/java/bio/terra/buffer/app/controller/ResourceApiControllerTest.java

Ticket: https://broadworkbench.atlassian.net/browse/CORE-553
The lack of a request body was causing issues when I called the client library method in Rawls.

[CORE-553] Fix Repair Project API
