DataBiosphere/terra-resource-buffer

src/main/java/bio/terra/rbs/service/pool/AlwaysPassValidator.java
src/main/java/bio/terra/rbs/service/pool/DefaultResourceConfigValidator.java
src/main/java/bio/terra/rbs/service/pool/GcpResourceConfigValidator.java
src/main/java/bio/terra/rbs/service/pool/PoolConfigLoader.java
src/main/java/bio/terra/rbs/service/pool/ResourceConfigValidator.java
src/main/java/bio/terra/rbs/service/pool/ResourceConfigValidatorFactory.java
src/main/resources/config/dev/resource-config/aou_ws_0_0_1.yml
src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
src/test/java/bio/terra/rbs/service/pool/ResourceConfigValidatorTest.java

Now we always create networks/subnets for a project. And it requires billing account and enabling compute api. 
So having a check here to catch error earlier.

[PF-200] Add few basic validations for GCP resource Config

---

src/test/java/bio/terra/rbs/db/RbsDaoTest.java
src/test/java/bio/terra/rbs/integration/CreateProjectFlightIntegrationTest.java
src/test/java/bio/terra/rbs/integration/DeleteProjectFlightIntegrationTest.java
src/test/java/bio/terra/rbs/integration/IntegrationUtils.java
src/test/java/bio/terra/rbs/integration/RbsIntegrationTest.java
src/test/java/bio/terra/rbs/service/pool/PoolServiceTest.java
src/test/java/bio/terra/rbs/service/resource/flight/LatchStepTest.java
src/test/resources/application-integration-enable-scheduler.yml

1. BEFORE_EACH_TEST_METHOD should be AFTER, as we want to mark the ApplicationContext dirty after test.
2. Reduce polling period and increase polling number
3. `Duration.plus` returns a copy of the duraion, so we need to use the new copy: 
`waited = waited.plus(Duration.ofMillis(poll.toMillis())); `
4. Reduce flight-submission-period in test

[PF-217] Few improvements in test to reduce test time

---

src/main/java/bio/terra/rbs/db/RbsDao.java
src/main/resources/db/changesets/20200925_initial_schema.yaml
src/test/java/bio/terra/rbs/db/RbsDaoTest.java

In my next PR, there will be a scheduler:
```
List<Resource> resources = rbsDao.retrieveResourceToCleanup();
for(Resource resource : resources) {
publish(resource);
insertCleanupRecord(resource.id());
}
```

[PF-196] Add cleanup_record table to track the resources published to Janitor

---

local-dev/run_local.sh
src/main/resources/api/service_openapi.yaml

Initially we mix use `googleoauth` with `authroization` in request header

[no ticket ] Fix client library's security schema issue and local runner script config

---

build.gradle
src/main/java/bio/terra/buffer/app/controller/BufferApiController.java
src/main/resources/api/service_openapi.yaml
src/test/java/bio/terra/buffer/app/controller/BufferApiControllerTest.java

Similar to what TDR did: https://github.com/DataBiosphere/jade-data-repo/pull/631
Body can not be null for jersey2 client library

[PF-254]: Move handout request id into requestBody for put operation

---

src/main/java/bio/terra/buffer/app/configuration/PrimaryConfiguration.java
src/main/java/bio/terra/buffer/service/stairway/StairwayComponent.java
src/main/resources/application.yml

Background: Each project creation is a flight and it block a thread for 10~15 minutes. We need more threads to be able to fill the pool sooner.
Things in the PR:
1.  Set stairway name - because without the name every-time we restart Buffer server it will create a new stairway name, and we can not recover the previous one. 
2. Add more threads for stairway - We need more threads to make is faster to fill a pool. 
3. Don't swipe flight log when flight finished - Flightlog is useful for debug purpose.

[PF-287] Improve Stairway setup in Buffer service

---

src/main/java/bio/terra/buffer/common/ResourceId.java

Found a bug in Stairway  https://broadworkbench.atlassian.net/browse/PF-316
After Stariway put value into Stairway db then retrieve it from db, seems it loses initial object type. 
So I have this work-around that stores String as raw type, and let Buffer Code to serialize/deserialize

[no ticket] Use String not uuid when storing value into Stairway

---

src/main/resources/config/dev/pool_schema.yml
src/main/resources/config/tools/pool_schema.yml

The pool size is estimated from the qps of how many test are triggerd. 
AoU has a higher number because it seems to have more tests triggered

[no ticket] Increase pool size for tools and dev

---

src/main/resources/config/dev/pool_schema.yml
src/main/resources/config/dev/resource-config/workspace_manager_v5.yml
src/main/resources/config/perf/pool_schema.yml
src/main/resources/config/perf/resource-config/workspace_manager_v5.yml
src/main/resources/config/tools/pool_schema.yml
src/main/resources/config/tools/resource-config/workspace_manager_v4.yml

Add "notebooks.googleapis.com" to the `enabledApis`. We need this API for working with AI Platform Notebooks.
Planed process:
1. Wait for this to roll out to associated buffer deployments
2. Update the `terra-helmfile` repo to update the workspace manager configs for the new pool id. (https://github.com/broadinstitute/terra-helmfile/pull/918)
3. Wait for redeployments in all workspace manager environments
4. Delete the obsolete workspace_manager pools here.

PF-338 Enable notebooks API for workspace_manager configs

---

buffer-clienttests/build.gradle

Bump Test Runner library version from 0.0.1-SNAPSHOT to 0.0.2-SNAPSHOT.
This bump includes a change so that the isFailure flag is set on errors in the setup/cleanup methods, in addition to the userJourney methods. This should cause the GH action to fail if there is an exception in the setup/cleanup methods also. Previously, it only failed if there was an exception in the userJourney methods.

PF-440: Bump test runner library version.

---

.github/workflows/trivy.yml

This change adds Trivy security scan for the Docker image, as discussed in the Workbench Cross-Team meeting.
The action will run on every PR and give you feedback if the Docker image contains critical OS vulnerabilities.
More info:
https://github.com/broadinstitute/dsp-appsec-trivy-action
https://github.com/broadinstitute/dsp-appsec-blessed-images

[PF-365] Add AppSec Github Trivy Action

---

src/main/java/bio/terra/buffer/app/configuration/PrimaryConfiguration.java
src/main/java/bio/terra/buffer/service/resource/FlightScheduler.java
src/main/resources/application.yml
src/test/java/bio/terra/buffer/service/resource/FlightSchedulerTest.java
src/test/resources/application-integration-enable-scheduler.yml

This is the short-term of 'Primary Job' in Buffer doc:
https://docs.google.com/document/d/1rSIXOrDQYCgptHZIxnxXjM-nHjb_ohxxNGKAl5ZarKw/edit#heading=h.5inn55b6pv26
As Doug suggested "For: down sizing... Currently we don't really need to actively reduce the size"
This also increases the frequency of scheduling service runs.

[PF-619] Disable deleting resource when exceeding pool size

---

build.gradle

No longer log warnings to bring the buffer in line with other services.

PF-618 Only log errors and fatals from the cloud profiler agent.

---

local-dev/run_local.sh
src/main/java/bio/terra/buffer/service/resource/FlightScheduler.java
src/main/resources/db/changelog.xml
src/main/resources/db/changesets/20210405_add_resource_state_index.yaml

1. AoU also has a similar buffer service. Recently we observe slowness in the AoU buffer service when handout resource. That is caused by too many non-READY resource slows down query. As our resource table is heavily used by handout, schedulling service, I think it make sense to add index.
2. Also, remove the unnecessary query when deleting resources(a Pool is deactivated for a while, we are still trying to make a query on that table everytime).
3. Fix env variable in local run script.
```
testdb=> select *
from pg_indexes where tablename = 'resource';
schemaname | tablename |      indexname       | tablespace |                                   indexdef                                    
------------+-----------+----------------------+------------+---------------------------------------- …
```

[PF-561]: Few minor improvements: Add index on resource table, avoid on unnecessary db query

---

src/main/java/bio/terra/buffer/service/cleanup/CleanupScheduler.java

Setting the expiration twice on subsequent lines doesn't do anything. tiny nit fix.

[no ticket] remove redundant expiration field set.

---

src/main/java/bio/terra/buffer/service/pool/GcpResourceConfigValidator.java
src/test/java/bio/terra/buffer/service/pool/ResourceConfigValidatorTest.java

Initially we have restriction that all pool config must have compute API enabled because those projects power “Terra workspace” which means user need compute. But with Buffer Service adopted by Data Repo, that’s true anymore. 
We may want to remove this restriction and unblock TDR integration

[PF-806]remove compute api restriction

---

src/main/resources/config/tools/pool_schema.yml

Added the `workspace_manager_v4` pool to the schema for the tools environment.
The current `v6` pool does not delete the default compute engine service account or the default VPC network. This was to support Nextflow, which required both of these things. Now there is a Nextflow edge release that allows overriding both defaults.
I am enabling the `v4` pool for the tools environment to test this against my personal environment WSM and updated CLI code. Once I confirm that works, I'll make a similar change here to enable the `v5` pool for the dev environment. (Tools pool id went from `v4`->`v6`, dev went from `v5`->`v6`) And then update the helmfile for all WSM deployments to point to these pools.

PF-538 (part 1): Add workspace_manager_v4 pool for tools environment.

---

src/main/resources/config/dev/pool_schema.yml
src/main/resources/config/dev/resource-config/workspace_manager_v8.yml
src/main/resources/config/tools/pool_schema.yml
src/main/resources/config/tools/resource-config/workspace_manager_v8.yml

Added the `workspace_manager_v8` pool and accompanying resource config to the tools and dev environment. These resource configs are identical to the `_v5` for dev and `_v4` for tools. They are copy/pasted into a new file to make future cleanup easier (see review comments).
The new pools do not delete the default compute engine service account or the default VPC network. This was to support Nextflow, which required both of these things. Now there is a Nextflow edge release that allows overriding both defaults.
I've tested this against my personal environment WSM and updated CLI code. Next I will update the helmfile for all WSM dev/tools deployments to point to these pools.

PF-538 (part 2): Add workspace_manager_v8 pools for tools, dev environments.

---

src/main/resources/config/perf/pool_schema.yml
src/main/resources/config/perf/resource-config/cwb_ws_perf_v2.yml
src/main/resources/config/perf/resource-config/vpc_sc_v2.yml
src/main/resources/config/prod/pool_schema.yml
src/main/resources/config/prod/resource-config/cwb_ws_prod_v2.yml
src/main/resources/config/prod/resource-config/vpc_sc_v2.yml

In order to keep projects consistent across envs, we discussed creating new pools: #168 (comment) This PR handles that extra change.
related PR: https://github.com/broadinstitute/firecloud-develop/pull/2596

[ca-1434] created new pools for perf/prod in order to remove unused notebook API

---

.github/workflows/master_push.yml

My [last PR](https://github.com/DataBiosphere/terra-resource-buffer/pull/174) attempted to fix the tag/build/push github action, but it did not run due to ignoring `.github/**`.  This PR removes that ignore so that future changes to the action will get applied immediately.  I also add a `workflow_dispatch` to allow manual running of the action.

Add workflow_dispatch for tag/build/push task.

---

src/main/java/bio/terra/buffer/app/configuration/CrlConfiguration.java

Most of perf tests(AoU, Buffer, Terra) happens at midnight - 4am. We should avoid keeping Janitor busy during that time. Change to 10 hrs seems can make janitor avoid that busy time slot.
As-is, we've seen the janitor 429 trying to delete projects with the following error message.
`Quota exceeded for quota metric 'Write requests' and limit 'Write requests per minute' of service 'cloudresourcemanager.googleapis.com' for consumer 'project_number:191683885592'`

[no ticket]: Increase how long to keep the resource before asking Janitor to delete it.  

---

src/main/java/bio/terra/buffer/service/pool/GcpResourceConfigValidator.java
src/main/java/bio/terra/buffer/service/resource/flight/CreateProjectStep.java
src/main/java/bio/terra/buffer/service/resource/flight/GenerateProjectIdStep.java
src/main/java/bio/terra/buffer/service/resource/flight/GoogleProjectCreationFlight.java
src/main/java/bio/terra/buffer/service/resource/projectid/GcpProjectIdGenerator.java
src/main/resources/config/tools/pool_schema.yml
src/main/resources/config/tools/resource-config/workspace_manager_v9.yml
src/test/java/bio/terra/buffer/integration/CreateProjectFlightIntegrationTest.java
src/test/java/bio/terra/buffer/service/pool/ResourceConfigValidatorTest.java

- Added length validation to the GCP project id generation. Check that the length is <= 30 ([ref](https://cloud.google.com/resource-manager/docs/creating-managing-projects#:~:text=A%20project%20ID%20must%20start,between%206%20and%2030%20characters.&text=You%20can't%20use%20certain,new%20project%20with%20the%20projects.)).
- Moved the check for whether the project id is already in use from the `CreateProjectStep` to the `GenerateProjectIdStep`, and try to generate another id if the generated one is already in use.
- Restricted the project id prefix length to 12 characters. This only applies when using the `TWO_WORDS_NUMBER` naming scheme. I chose 12 because on average we get a valid project id on the second try. Some prefixes will have to be shortened to meet this requirement (e.g. …

PF-228: Validate generated project id. Restrict prefix length.

---

src/main/java/bio/terra/buffer/app/configuration/CrlConfiguration.java
src/main/java/bio/terra/buffer/service/resource/flight/CreateDnsZoneStep.java
src/main/java/bio/terra/buffer/service/resource/flight/CreateResourceRecordSetStep.java
src/main/java/bio/terra/buffer/service/resource/flight/CreateRouteStep.java
src/main/java/bio/terra/buffer/service/resource/flight/CreateSubnetsStep.java
src/main/java/bio/terra/buffer/service/resource/flight/GoogleProjectConfigUtils.java
src/main/resources/config/resource_schema.yaml
src/test/java/bio/terra/buffer/integration/CreateProjectFlightIntegrationTest.java
src/test/java/bio/terra/buffer/service/resource/flight/GoogleProjectConfigUtilsTest.java

Background: When RBS is designed, private Google Access + Flow logs is just used by AoU, so we combined them into enableNetworkMonitroring. 
But with the new Cromwell requirements, it wants all CWB projects having private Google Access Enabled but disable flow logs.
So I split them back to two.
If private Google Access is true, we will:
1. Set this value in Subnets
2.  Create private DNS record
3. Record sets
4. Create Custom static Route.
All steps is https://cloud.google.com/vpc/docs/configure-private-google-access
And https://github.com/broadinstitute/gcp-dm-templates/blob/bf2ec422869d108670ea34f93db3e19d5d07b017/firecloud_project.py

[PF-924]Add private Google Access flag to controll whether to enable private Google Access

---

src/main/resources/config/dev/pool_schema.yml
src/main/resources/config/dev/resource-config/workspace_manager_v9.yml
src/test/java/bio/terra/buffer/service/resource/projectid/GcpProjectIdGeneratorTest.java

- Added a new dev WSM pool that uses the `TWO_WORDS_NUMBER` project naming scheme, and a shorter prefix than before (`terra-wsm-dev`->`terra-wsm-d`). There is already a tools WSM pool that I tested on my personal environment WSM deployment and confirmed that projects with the new naming scheme are returned when creating a new workspace.
- Added a unit test for when the maximum number of retries have been exhausted in generating a new project id.
I'm planning to remove the previous `workspace_manager_v8` pools in a follow-on PR once I move all the deployments over to using the new `workspace_manager_v9` pools.

PF-228 (part 2): Add new dev WSM pool with new naming scheme.

---

local-dev/setup_gke_deploy.sh
local-dev/skaffold.yaml.template

DevOps is preparing to make some structural changes to the terra-helmfile repo; this PR updates buffer's Skaffold development workflow to be resilient to those changes. Changes include:
* Remove references to `terra-helm`
* Render manifests using `terra-helmfile`'s `render` tool instead of invoking `helm` with hardcoded values file paths
* Use Skaffold's kubectl deployment option to deploy these rendered manifests
I have tested these changes by deploying buffer to the `gmalkov` personal environment.

DDO-1319 Update local dev workflow for buffer to use render

---

src/main/java/bio/terra/buffer/app/configuration/CrlConfiguration.java
src/main/resources/config/resource_schema.yaml
src/test/java/bio/terra/buffer/integration/CreateProjectFlightIntegrationTest.java

Set it to longer period so developers can have time to check projects and debug test failures...

[no ticket][risk=no]Increase how long to keep resource before Janitor delete it

---

src/main/java/bio/terra/buffer/service/resource/flight/CreateSubnetsStep.java
src/main/resources/config/alpha/pool_schema.yml
src/main/resources/config/alpha/resource-config/vpc_sc_v4.yml
src/main/resources/config/dev/pool_schema.yml
src/main/resources/config/dev/resource-config/vpc_sc_v4.yml
src/main/resources/config/perf/pool_schema.yml
src/main/resources/config/perf/resource-config/vpc_sc_v5.yml
src/main/resources/config/prod/pool_schema.yml
src/main/resources/config/prod/resource-config/vpc_sc_v5.yml
src/main/resources/config/staging/pool_schema.yml
src/main/resources/config/staging/resource-config/vpc_sc_v4.yml
src/main/resources/config/tools/pool_schema.yml
src/main/resources/config/tools/resource-config/vpc_sc_dev-fiab_v4.yml
src/main/resources/config/tools/resource-config/vpc_sc_qa-fiab_v4.yml

Background context: We are seeing increase cost when using dataproc. And it turns out caused by flow log cost.
I think master node and worker nodes communicates a lot hence generates lot of flow logs.
This PR filter out those logs that generated within VPC-SC.

[RW-7587][risk=no]: Add flow log filter that filter out inter-VPC network traffic 

---

src/main/java/bio/terra/buffer/service/resource/flight/CreateStorageLogBucketStep.java
src/main/java/bio/terra/buffer/service/resource/flight/GoogleProjectConfigUtils.java
src/main/resources/config/resource_schema.yaml
src/test/java/bio/terra/buffer/integration/CreateProjectFlightIntegrationTest.java

The log bucket created uses object-level ACLs, and this doesn't satisfy the UBLA security rule. This change adds a Storage configuration group with a single entry for `createLogBucket`.

[PF-1022] make log bucket creation configurable

---

local-dev/run_local.sh
src/main/java/bio/terra/buffer/app/configuration/CrlConfiguration.java
src/main/java/bio/terra/buffer/service/cleanup/CleanupScheduler.java
src/test/java/bio/terra/buffer/service/cleanup/CleanupSchedulerTest.java

Background: Using a static variable as time to live make it impossible to customize this value per env. 
However, we did see a request from TDR and Leo that wants to have different values.

[PF-1278] Allow customize test resource time to live per env

---

src/main/java/bio/terra/buffer/service/resource/flight/CreateSubnetsStep.java

There are now regions in blocklist that aren't in `REGION_TO_IP_RANGE` (see [here](https://github.com/verily-src/terra-deployment/pull/443)) so the warning no longer makes sense.

[PF-1152] Delete region blocklist warning

---

buffer-clienttests/src/main/resources/configs/HandoutResourcesThenWaitForRefill.json

Recently RBS perf tests became flaky and often times out. Seems there are more and more services that consuming GCP quota from terra-kernel-k8s project, and slow down project creation.
Decrease the number of projects to create per perf test, and increase the timeout. 
The new config (200 concurrent) is still good enough to capture RBS latency issues, the actual QPS in Community workbench is <0.001/s.

[no ticket] Update RBS perf test config to consume less resources

---

buffer-clienttests/build.gradle

The latest TestRunner version was a breaking change that refactored test parameters from List<String> to Map<String,String>. 
RBS doesn't have any TestRunner changes with parameters so no migration is necessary, but upgrading now means we won't have to migrate tests anyone writes in the future.

[PF-1291] Bump test runner version

---

buffer-clienttests/src/main/resources/configs/HandoutResourcesThenWaitForRefill.json
src/main/resources/config/buffertest/pool_schema.yml

Last night's run timed out:
https://github.com/DataBiosphere/terra-resource-buffer/runs/5109523341?check_suite_focus=true
`HandoutResourcesThenWaitForRefill` timed out after 2 hours.
A passing run from a couple days ago:
https://github.com/DataBiosphere/terra-resource-buffer/runs/5032679956?check_suite_focus=true
`HandoutResourcesThenWaitForRefill` took about 1 hr 50 mins.

Fix perf test flakiness by reducing numberOfUserJourneyThreadsToRun

---

src/main/resources/config/dev/pool_schema.yml

From Rawls:
```
Server Error error: ErrorReport(Rawls,{"causes":[],"exceptionClass":"bio.terra.buffer.client.ApiException","message":"{\"message\":\"Invalid pool id: vpc_sc_v6.\",\"statusCode\":400,\"causes\":[]}","source":"rawls","stackTrace":
```

Add the vpc_sc_6 dev pool back in, still in use by Rawls

---

src/main/resources/config/dev/pool_schema.yml

This reverts commit bbced2db0e5819e906c74c732301773c2e3d2b23.
See https://github.com/DataBiosphere/terra-resource-buffer/pull/223#issuecomment-1067972458

Revert "Add the vpc_sc_6 pool back in, still in use by Rawls (#223)"

---

src/main/java/bio/terra/buffer/db/BufferDao.java
src/main/java/bio/terra/buffer/service/pool/PoolService.java
src/test/java/bio/terra/buffer/service/pool/PoolServiceTest.java

As described in [this document](https://docs.google.com/document/d/1aXOF_0T_Qje4O5KbcKqgNPGhnytm97dPSBaGnzNtEUY/edit?usp=sharing&resourcekey=0-Vwd3zNcBNJ7mbbGq0OuflA), implementing pool re-activation after deactivation. Simply add the pool back into the schema file and it should clear the expiration and set the status back to ACTIVE. The scheduler should add flights to return the pool to its stated size.

[PF-1415] reactivate de-activated pools

---

src/main/resources/config/dev/pool_schema.yml
src/main/resources/config/perf/pool_schema.yml
src/main/resources/config/prod/pool_schema.yml

I left an extra 2 versions in prod to allow for potential rollback. I also noted some versions in alpha+staging, which are definitely unused by AoU. I'm not comfortable touching these without knowing their purpose, can check with @yonghaoy when he's back. By my estimate they could simply be deleted.
I'm also noticing that all historical pool config yaml files appear to be preserved, so I haven't touched those.

Drop some unused AoU pools

---

buffer-clienttests/build.gradle

This should fix the broken nightly perf tests (https://github.com/DataBiosphere/terra-resource-buffer/actions/runs/2165571559) caused by RBS no longer pulling in the Apache lang 2 package that TestRunner implicitly depended on.

Use latest version of TestRunner

---

.github/actions/bump-skip/action.yml
.github/workflows/master_push.yml
build.gradle
settings.gradle

(similar to https://github.com/DataBiosphere/terra-resource-janitor/pull/136)
RBS's `tag-build-push` workflow is currently broken because it uses `broadinstitute/github-tag-action` instead of `databiosphere/github-actions/actions/bumper`. The old action hasn't been updated since 2020, and recently broke due to git's mitigation of CVE-2022-24765 (see example workaround in https://github.com/DataBiosphere/github-actions/pull/32). Rather than fix a second bumper action, I think it makes sense to use the action currently supported by Broad devops.
This change includes:
- Swapping `broadinstitute/github-tag-action` to `databiosphere/github-actions/actions/bumper`, plus a handful of related changes inside the `tag-build-push` workflow inspired by [WSM's …

[PF-1557] Follow WSM pattern for publishing

---

.github/workflows/master_push.yml

This action updates the version number in `settings.gradle`. In order to merge this change to the main branch without reviews, this must be done as an admin (in this case Broadbot). I've already set up the BROADBOT_TOKEN secret via the Vault -> GHA secrets terraform.

[PF-1557] Update master_push.yml

---

.github/workflows/test.yml

Version bumping with Broadbot is now running, but we're running tests on both the version bump commit and the real commit that triggered the bump. This will skip running tests for the version bump commit, similar to what we do for WSM.

[PF-1557] Skip test GHA on version bump

---

.github/workflows/master_push.yml
.github/workflows/test-runner-nightly-perf.yml
.github/workflows/test.yml

These workflows are masking secrets incorrectly, the masking needs to happen before setting them as output. If this workflow is run with debug logging (which it isn't), the current pattern will leak secrets.

Fix GHA secret masking

---

.github/workflows/test.yml
.github/workflows/trivy.yml

Follow-up on similar changes in Terra-cli - https://github.com/DataBiosphere/terra-cli/pull/327
---
Issue - If changeset only has .md files (readme.md for example) the PR check (github workflow) does not report the status as success skipped, thus leading to a PR that can't be merged
As a workaround remove this config for now
Further work will be carried out in https://broadworkbench.atlassian.net/browse/PF-2048

[PF-2049] terra-resource-buffer: Remove paths ignore from Github workflows

---

build.gradle

Problem statement - Standard eclipse temurin images potentially have app-security concerns
Fix - use the broad app-security-approved images from https://github.com/broadinstitute/dsp-appsec-blessed-images
No further checks were performed since the major version is the same, minor version is a downgrade

[PF-940] Use broad-appsec-blessed JRE image

---

.github/workflows/master_push.yml
local-dev/skaffold.yaml.template

This needs to be merged (and a new image needs to be published) before the equivalent helmfile change can merge

[PF-2168] Move from terra-kernel-k8s to broad-dsp-gcr-public

---

.github/workflows/master_push.yml

#258 revealed that the publishing workflow was broken, this fixes the workflow. This moves to a Github secret based flow and removes Vault usage from this workflow.

[PF-2168] Fix publishing workflow

---

.github/workflows/test.yml
.github/workflows/trivy.yml

Only run PR checks when the PR targets primary/default branch
currently, all PRs (irrespective of the branch they target) automatically trigger PR checks. This is unnecessary and may cause the checks to be queued up on GitHub runner.
ref - 
- https://github.com/DataBiosphere/terra-workspace-manager/pull/1061
- https://broadworkbench.atlassian.net/browse/PF-2478

[PF-2478] Only run checks when PR targets default branch

---

.github/workflows/master_push.yml

The existing `repository-dispatch` based notification flow is broken, and publishing workflows have been broken for several weeks (though no real PRs were added in that time).

[PF-2511] Fix workflow to notify Broad devops

---

.github/actions/bump-skip/action.yml
.github/workflows/master_push.yml
.github/workflows/test-runner-nightly-perf.yml
.github/workflows/test.yml
.github/workflows/trivy.yml

Replace deprecated commands in GH actions & workflows.
- use actions/setup-java@v3 instead of v2
- use actions/checkout@v3 instead of v2
- use actions/cache@v3 instead of v2
- use actions/upload-artifact@v3 instead of v2
- use setup-node@v3 instead of v2
- replace 'set-output' command

[TERRA-434] Replace deprecated commands in GH actions & workflows

---

src/main/resources/config/dev/pool_schema.yml
src/main/resources/config/dev/resource-config/workspace_manager_v10.yml
src/main/resources/config/tools/pool_schema.yml
src/main/resources/config/tools/resource-config/workspace_manager_v10.yml

Adds a new WSM pool with `bigquerydatatransfer.googleapis.com` enabled and no other changes over v9 for `tools` and `dev` environments, which are the only Broad environments which use WSM-managed GCP projects.
I'll remove the v9 pool in a few days after configuring all instances to use the v10 pool instead.

[PF-2639] Add new pool for WSM with BigQuery Transfer API enabled

---

src/main/resources/config/dev/pool_schema.yml
src/main/resources/config/tools/pool_schema.yml

Followup to #265, all WSM instances are now using the v10 pool and I've confirmed the `tools` and `dev` v9 pools have had 0 handout requests for several days.

[PF-2639] Remove v9 configuration

---

src/main/java/bio/terra/buffer/service/pool/GcpResourceConfigValidator.java
src/main/java/bio/terra/buffer/service/resource/projectid/GcpProjectIdGenerator.java
src/test/java/bio/terra/buffer/service/pool/ResourceConfigValidatorTest.java

Currently, RBS only validates prefix length for pool names using the `TWO_WORDS_NUMBER` scheme. However, it will also fail to produce valid names with the `RANDOM_CHAR` scheme if the prefix is too long (currently >22 characters). This adds explicit validation so that pool configuration fails earlier instead of each flight failing individually.

[PF-2844] Add explicit validation for RANDOM_CHAR pattern

---

build.gradle
gradle.lockfile

This pulls in the latest version of TCL with an update to the `grpc-xds` library (https://github.com/DataBiosphere/terra-common-lib/pull/114)

[PF-2904] Update TCL version

---

src/main/resources/config/tools/pool_schema.yml

https://broadworkbench.atlassian.net/browse/DC-814
________
We've been seeing a lot of test flakiness around RBS over the last couple of weeks. After other debugging attempts (detailed in [datarepo PR](https://github.com/DataBiosphere/jade-data-repo/pull/1579)), I'd like to try bumping up the pool size. The recent errors have been due to not enough projects being available and the retries did not work, so potentially bumping up the pool size will provide some relief.

DC-814: Increase datarepo tools pool size

---

.github/dependabot.yml

Based on the [WSM dependabot file](https://github.com/DataBiosphere/terra-workspace-manager/blob/main/.github/dependabot.yml), though with no ignores. We can add ignores as needed.

Enable dependabot (WOR-1745).

---

.github/actions/write-credentials/action.yml
.github/workflows/test.yml
gradle/testing.gradle
src/main/java/bio/terra/buffer/app/configuration/CrlConfiguration.java
src/test/resources/application-integration.yml

As part of [WOR-1745](https://broadworkbench.atlassian.net/browse/WOR-1745), we need to change how the CI pipeline gets the SA credentials so that dependabot is able to run the tests (related PR is https://github.com/broadinstitute/terraform-ap-deployments/pull/1623).
[WOR-1745]: https://broadworkbench.atlassian.net/browse/WOR-1745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Switch to writing credentials from secrets for integration tests (WOR-1745).

---

build.gradle
src/main/java/bio/terra/buffer/common/MetricsHelper.java
src/test/java/bio/terra/buffer/common/MetricsHelperTest.java

Ticket: [WOR-1744](https://broadworkbench.atlassian.net/browse/WOR-1744)
* Switch resource counter to gauge to report current resource counts instead of total number of resources in each count over pod lifespan
* Bump TCL version to pull in fix from https://github.com/DataBiosphere/terra-common-lib/pull/197 
Counter before would increase by the count of resources in a given state every time metrics were recorded (pool size of 5):
```
terra_buffer_resource_resource_state_count_num_per_pool_total{otel_scope_name="bio.terra.common.stairway.MetricsHelper",pool_id="resource_toolsalpha_v8",pool_status="ACTIVE",resource_state="CREATING"} 71.0
terra_buffer_resource_resource_state_count_num_per_pool_total{otel_scope_name="bio.terra.common.stairway.MetricsHelper",pool_id="resource_toolsalpha_v8",poo …
```

[WOR-1744] Switch resource counter to gauge and bump TCL

---

.github/workflows/master_push.yml

Ticket: [WOR-1811](https://broadworkbench.atlassian.net/browse/WOR-1811)
* duplicate step in GHA workflow that sets dev version to also set tools version which is used by BEEs
[WOR-1811]: https://broadworkbench.atlassian.net/browse/WOR-1811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WOR-1811] Set tools version when merging to master

---

build.gradle

Update to https://github.com/DataBiosphere/terra-common-lib/releases/tag/1.1.19
- remove otel dependencies to fix issue with otel/spring version conflicts
Verified by running `./local-dev/run_local.sh` and using http://localhost:9098/metrics to look at metrics

Update RBS to the latest tcl

---

build.gradle
src/main/java/bio/terra/buffer/app/StartupInitializer.java
src/main/java/bio/terra/buffer/app/configuration/CrlConfiguration.java
src/main/java/bio/terra/buffer/app/configuration/DbCleanupJobConfiguration.java
src/main/java/bio/terra/buffer/app/configuration/ShedlockConfiguration.java
src/main/java/bio/terra/buffer/common/MetricsHelper.java
src/main/java/bio/terra/buffer/db/BufferDao.java
src/main/java/bio/terra/buffer/db/DbCleanupJob.java
src/main/java/bio/terra/buffer/service/cleanup/JanitorResourceCleanupScheduler.java
src/main/java/bio/terra/buffer/service/pool/PoolConfigLoader.java
src/main/java/bio/terra/buffer/service/resource/flight/CreateProjectStep.java
src/main/java/bio/terra/buffer/service/resource/flight/CreateRouterNatStep.java
src/main/java/bio/terra/buffer/service/resource/flight/GoogleProjectConfigUtils.java
src/main/java/bio/terra/buffer/service/resource/flight/GoogleUtils.java
src/main/java/bio/terra/buffer/service/resource/flight/StepUtils.java
src/main/resources/application.yml
src/main/resources/db/changelog.xml
src/main/resources/db/changesets/20240926_add_cleanup_created_at.yaml
src/main/resources/db/changesets/20240926_shedlock.yaml
src/test/java/bio/terra/buffer/config/PoolSchemaTest.java
src/test/java/bio/terra/buffer/db/BufferDaoTest.java
src/test/java/bio/terra/buffer/db/DbCleanupJobTest.java
src/test/java/bio/terra/buffer/integration/IntegrationUtils.java
src/test/java/bio/terra/buffer/service/cleanup/CleanupSchedulerTest.java

The `resource` and `cleanup_record` tables are only ever appended to, and grow without bound. This can cause performance issues as the DB eventually struggles to manage these ever-larger tables.
* I've introduced a scheduled job that will find all records in these tables and delete those that are eligible for cleanup, up to a limit. This job is scheduled via Spring's [scheduling](https://spring.io/guides/gs/scheduling-tasks) mechanism. This introduces a divergence from the current pattern in the codebase of [using](https://github.com/DataBiosphere/terra-resource-buffer/blob/master/src/main/java/bio/terra/buffer/service/cleanup/CleanupScheduler.java#L43) a [ScheduledExecutorService](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ScheduledExecutorService.ht …

[WOR-1816] Scheduled DB cleanup job

---

build.gradle
gradle/dependency-locking.gradle
terra-resource-buffer-client/build.gradle

This dependency is updated in upstream dependencies so we do not need this constraint anymore. This will also prevent dependabot from attempting to upgrade to v4 which breaks tests. I ran a test scan via sourceclear and the related CVE this constraint was mitigating is no longer detected.

[WOR-1448] Remove protobuf-java constraint as upstream deps have upgraded to 3.25.5

---

build.gradle

See write-up in https://broadworkbench.atlassian.net/browse/CORE-104
`terra-resource-janitor-client:0.114.0-SNAPSHOT` is a non-working version. It was created in June 2022, most likely during development, and contains some changes to the PubSub message contract with Janitor.
The actual latest version is `0.113.37-SNAPSHOT`, which was published in Sep 2024.
I think this was inadvertantly [upgraded by dependabot](https://github.com/DataBiosphere/terra-resource-buffer/pull/323/) in July 2024. As a result, GCP project deletion in test environments has been broken since July 2024.
I'll also to try to remove the "bad" version in Artifactory, and make improvements on the Janitor side to not fail on unknown fields in messages. But first I am fixing the `janitor-client` dependency in RBS.

CORE-104: Fix janitor client dependency

---

.github/workflows/test.yml
local-dev/local-postgres-init.sql

For unit tests, and unit tests only, upgrade to Postgres 16.3.
16.3 is the version supported by Google: https://cloud.google.com/sql/docs/postgres/db-versions
This change allows us to get some burn-in on Postgres 16 before upgrading any live environments.
_reviewer: the Codacy failures on this PR sure look like false positives to me._

CORE-3: upgrade to Postgres 16.3 for unit tests

---

src/main/resources/config/buffertest/pool_schema.yml
src/main/resources/config/buffertest/resource-config/resource_buffer_test_v3.yml
src/main/resources/config/dev/pool_schema.yml
src/main/resources/config/dev/resource-config/cwb_ws_resource_dev_v8.yml
src/main/resources/config/dev/resource-config/vpc_sc_v13.yml
src/main/resources/config/dev/resource-config/workspace_manager_v12.yml
src/main/resources/config/prod/pool_schema.yml
src/main/resources/config/prod/resource-config/cwb_ws_prod_v8.yml
src/main/resources/config/prod/resource-config/vpc_sc_v12.yml
src/main/resources/config/staging/pool_schema.yml
src/main/resources/config/staging/resource-config/cwb_ws_resource_staging_v8.yml
src/main/resources/config/staging/resource-config/vpc_sc_v7.yml
src/main/resources/config/tools/pool_schema.yml
src/main/resources/config/tools/resource-config/cwb_ws_resource_fiab_v8.yml
src/main/resources/config/tools/resource-config/cwb_ws_resource_quality_v11.yml
src/main/resources/config/tools/resource-config/vpc_sc_qa-fiab_v6.yml
src/main/resources/config/tools/resource-config/workspace_manager_v12.yml
src/main/resources/config/toolsalpha/pool_schema.yml
src/main/resources/config/toolsalpha/resource-config/resource_toolsalpha_v9.yml

In support of migrating workflow compute from LifesciencesAPI to the new Batch API, create new pools with the Batch API enabled.

AN-186 Add pool configs with Google Batch enabled

---

.github/workflows/trivy.yml
build.gradle

https://broadworkbench.atlassian.net/browse/CORE-118 states that upgrading the `jib` version causes our Trivy scan to fail.
What was actually happening is that upgrading `jib` caused the jib build to fail. The jib failure did not throw an error in GitHub Actions. The workflow continued on to attempt the Trivy scan, but since jib failed there was no docker image to scan, so Trivy threw an error. A previous PR illustrates that behavior here: https://github.com/DataBiosphere/terra-resource-buffer/actions/runs/11502274753/job/32016865400?pr=364
This PR contains the following changes:
1. In 48b1e491ffbbec569971d9e3fc9d65c800dfb316, update the GHA such that if jib fails to build a docker image, the GHA workflow fails at that point. You can look at the workflows run on that specific commit and …

CORE-118: update jib; surface jib errors

---

.github/workflows/test-runner-nightly-perf.yml

It looks like a recent PR (#398) had the side effect of reenabling Buffer's nightly perf tests, but they no longer work. I'd like to remove notifications to the #dsde-qa channel since it is used for monolith release triage and these are not release-blocking. Notifications will continue to go to other configured Slack channels.

[DDO-3972] Stop sending perf test notifications to #dsde-qa

---

.github/workflows/test-runner-nightly-perf.yml

The cache backend service has been rewritten from the ground up for improved performance and reliability. [actions/cache](https://github.com/actions/cache) now integrates with the new cache service (v2) APIs.
The new service will gradually roll out as of February 1st, 2025. The legacy service will also be sunset on the same date. Changes in these release are fully backward compatible.
More info here: https://github.com/marketplace/actions/cache

CORE-246 Upgrading to cache v4 

---

src/main/resources/config/tools/pool_schema.yml

Increase the datarepo tools pool size to prevent tests from blocking or failing unnecessarily.
This value was changed from 1500 to 2000: https://github.com/DataBiosphere/terra-resource-buffer/pull/293
And then was changed from 2000 to 1000: https://github.com/DataBiosphere/terra-resource-buffer/pull/374
The usage of this pool depends heavily on how much work is being done on TDR. If there are more than three developers creating one or two branches each, a pool size of 1000 can be exhausted due to concurrent test execution. In addition to more activity, recent changes to allow integration tests to run in parallel, and to avoid needing to "lock" an integration host to run tests on, may have put a greater burden on this resource.
Here's the pool usage graph of the last 7 days
The exhaustion …

DT-1342: Increase (revert back) TDR tools pool size from 1000 to 2000

---

build.gradle

https://broadworkbench.atlassian.net/browse/CORE-385 is a security finding on `json-smart`.
`json-smart` is pulled in by `com.azure:azure-identity`, which is pulled in by `bio.terra:terra-cloud-resource-lib`. However, RBS doesn't need those Azure libs.
This PR excludes the Azure libs from CRL, which in turn excludes `json-smart`.
Part of a group of PRs:
* https://github.com/broadinstitute/rawls/pull/3240
* https://github.com/DataBiosphere/terra-resource-buffer/pull/422
* https://github.com/broadinstitute/thurloe/pull/377

CORE-385: exclude azure libs from CRL

---

buffer-clienttests/build.gradle
build.gradle
settings.gradle

Jira ticket: https://broadworkbench.atlassian.net/browse/DDO-4107
**Summary of changes**
Updated the artifact source for this service to read artifacts from Google Artifact Registry instead of JFrog.
**What**
Modified the config to pull artifacts from GAR. No publishing changes were made.
**Why**
This is part of Phase 2 of the artifact migration effort to deprecated JFrog and consolidate artifacts in GAR.
**Testing these changes**
Relied on passing CI checks and tests. Artifact reading-related issues are expected to surface as pipeline failures. For example these jobs [here](https://github.com/DataBiosphere/terra-scientific-pipelines-service/actions/runs/15309876591/job/43071753325?pr=222) and [here](https://github.com/DataBiosphere/leonardo/actions/runs/15324072477/job/43114134405?pr=4858 …

DDO-4131 read from google artifact registry

---

buffer-clienttests/build.gradle
build.gradle
terra-resource-buffer-client/build.gradle

This is a copy of Dependabot PR #427, minus the com.google.cloud.opentelemetry:exporter-* 0.34->0.35 bump. You can review each commit to see exactly what I did.
description copied (with otel removed) from #427:
---
Bumps the minor-patch-dependencies group with 21 updates:
| Package | From | To |
| --- | --- | --- |
| [org.springframework.boot:spring-boot-starter-test](https://github.com/spring-projects/spring-boot) | `3.4.5` | `3.5.0` |
| [org.springframework.boot:spring-boot-starter-data-jdbc](https://github.com/spring-projects/spring-boot) | `3.4.5` | `3.5.0` |
| [org.springframework.boot:spring-boot-starter-web](https://github.com/spring-projects/spring-boot) | `3.4.5` | `3.5.0` |
| [org.springframework.boot:spring-boot-configuration-processor](https://github.com/spring-projects/spring- …

CORE-536: dependabot no otel

---

build.gradle
src/main/resources/application.yml

Previously, RBS declared `com.google.cloud.opentelemetry:exporter-trace` and `com.google.cloud.opentelemetry:exporter-metrics` as dependencies.
This PR removes those imports and replaces them with `io.opentelemetry:opentelemetry-sdk`.
RBS has some code ([example](https://github.com/DataBiosphere/terra-resource-buffer/blob/master/src/main/java/bio/terra/buffer/common/MetricsHelper.java)) that directly accesses OpenTelemetry classes, so some kind of dependency is needed. However, the GCP exporters are not necessary for the code to compile; only the otel SDK is needed.
TCL, which RBS also depends on, specifies the GCP exporters so should already be configured to push to GCP.
This PR is an attempt to bypass the errors in #433.
I have verified, by running RBS locally, that RBS's custom metrics …

CORE-536: slim down RBS's otel/GCP exporters dependencies

---

src/main/resources/config/buffertest/pool_schema.yml
src/main/resources/config/buffertest/resource-config/resource_buffer_test_v4.yml
src/main/resources/config/dev/pool_schema.yml
src/main/resources/config/dev/resource-config/cwb_ws_resource_dev_v9.yml
src/main/resources/config/dev/resource-config/vpc_sc_v14.yml
src/main/resources/config/dev/resource-config/workspace_manager_v13.yml
src/main/resources/config/prod/pool_schema.yml
src/main/resources/config/prod/resource-config/cwb_ws_prod_v9.yml
src/main/resources/config/prod/resource-config/vpc_sc_v13.yml
src/main/resources/config/staging/pool_schema.yml
src/main/resources/config/staging/resource-config/cwb_ws_resource_staging_v9.yml
src/main/resources/config/staging/resource-config/vpc_sc_v8.yml
src/main/resources/config/tools/pool_schema.yml
src/main/resources/config/tools/resource-config/cwb_ws_resource_quality_v12.yml
src/main/resources/config/tools/resource-config/vpc_sc_qa-fiab_v7.yml
src/main/resources/config/tools/resource-config/workspace_manager_v13.yml
src/main/resources/config/toolsalpha/pool_schema.yml
src/main/resources/config/toolsalpha/resource-config/resource_toolsalpha_v10.yml
src/test/java/bio/terra/buffer/config/resource-config/..data/ws_0_0_2.yml
src/test/resources/test/config/resource-config/ws_0_0_2.yml

Jira: https://broadworkbench.atlassian.net/browse/AN-655
LifeSciences API is going to be shutdown on July 8th. To prepare for that, this PR adds new pool configs without LifeSciences API

[AN-655] Add new pool configs without LifeSciences API

---

gradle/publishing.gradle
terra-resource-buffer-client/README.md
terra-resource-buffer-client/build.gradle
terra-resource-buffer-client/publish.sh

https://broadworkbench.atlassian.net/browse/CORE-593
As far as I can tell, resource buffer is published as an image to GCR.  It was only published to jfrog through a manually-run `publish.sh` script, which I've updated.

[CORE-593] Switch from jfrog to GAR

---

buffer-clienttests/build.gradle
build.gradle
terra-resource-buffer-client/build.gradle

This is a copy of #457 with one update reverted. See #457 for details.
This PR reverts the jackson update specific to the `buildscript` scope, which `jib` uses. This should fix the jib failure seen in #457.
Two commits in this PR:
1. the commit from #457 (this was branched off its branch)
2. the jackson revert

CORE-69: minor patch dependencies 6aa8a5704a

---

.github/dependabot.yml
buffer-clienttests/build.gradle

Jackson 2.19.2 is only specified for the `buildScript` classpath.
As of this writing, Jib requires this specific version, and we want Dependabot to leave it alone.
This PR adds an ignore clause to `.github/dependabot.yml` to ignore the 2.20.0 update, which causes problems seen in #461. This will only be effective until jackson releases a higher version. I am struggling to come up with a better way to handle NOT updating the Jib-specific dependency.

CORE-69: ignore jackson 2.19.2 for buildScript
